name: secufy_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  firebase_core: ^2.27.2
  firebase_auth: ^4.18.0
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.15.10
  firebase_database: ^10.5.0
  webview_flutter: ^4.7.0
  flutter_inappwebview: ^6.0.0
  firebase_storage: ^11.7.1
  cached_network_image: ^3.3.1
  firebase_messaging: ^14.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/secufy_logo.png
    - assets/imgs/secufy_texto.png
    - assets/imgs/back_image.png
    - assets/imgs/google.png
    - assets/imgs/gadiel.jpg
    - assets/imgs/medel.jpg
    - assets/imgs/angel.jpg
    - assets/imgs/ismael.jpg
    - assets/imgs/background_main.png
