// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfKG-BNZSW0lAaiOozcQonIVySdt0mMxE',
    appId: '1:791195499468:web:bc92e553af92e3fc7abb69',
    messagingSenderId: '791195499468',
    projectId: 'secufy-3c114',
    authDomain: 'secufy-3c114.firebaseapp.com',
    databaseURL: 'https://secufy-3c114-default-rtdb.firebaseio.com',
    storageBucket: 'secufy-3c114.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3zhbyGDHOk740BKRXvL993bjaVUXVtRE',
    appId: '1:791195499468:android:3f063b3c876238cb7abb69',
    messagingSenderId: '791195499468',
    projectId: 'secufy-3c114',
    databaseURL: 'https://secufy-3c114-default-rtdb.firebaseio.com',
    storageBucket: 'secufy-3c114.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASG9fwsz3NXKnTr2vrLplDjjNfNta7peM',
    appId: '1:791195499468:ios:996875262c00f7de7abb69',
    messagingSenderId: '791195499468',
    projectId: 'secufy-3c114',
    databaseURL: 'https://secufy-3c114-default-rtdb.firebaseio.com',
    storageBucket: 'secufy-3c114.appspot.com',
    iosClientId:
        '791195499468-lnh0kvb02k8b9mg0ctmfad6rddi2sqct.apps.googleusercontent.com',
    iosBundleId: 'com.example.secufyApp',
  );
}
